### ISSUE TITLE
chopsticks.tunnel.RemoteException in basic usage on Mac OS X

### ISSUE THREAD

**Issue by petmakris** [lordmauve/chopsticks#13] opened 2016-10-16 13:18 UTC
Executing in  Macosx box with cpython 2.7:

```
#!/usr/bin/env python
from chopsticks.tunnel import Tunnel
tun = Tunnel('localhost')
import time
print('Time on %s:' % tun.host, tun.call(time.time))
```

Results to 

```
Traceback (most recent call last):
  File "./py0.py", line 11, in <module>
    print('Time on %s:' % tun.host, tun.call(time.time))
  File "/Users/username/example/.chopsticks/lib/python2.7/site-packages/chopsticks/tunnel.py", line 179, in call
    raise RemoteException(ret.msg)
chopsticks.tunnel.RemoteException: Unexpected EOF on stream
```

And the same if not executing from a virtualenv

```
Traceback (most recent call last):
  File "./py0.py", line 11, in <module>
    print('Time on %s:' % tun.host, tun.call(time.time))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/chopsticks/tunnel.py", line 179, in call
    raise RemoteException(ret.msg)
chopsticks.tunnel.RemoteException: Unexpected EOF on stream
```

Same scripts works when executed against a linux box.

```
('Time on localhost:', 1476624529.645448)
```

**Comment by lordmauve** [comment] 2016-10-16 13:47
If you type 'ssh localhost python' at a bash prompt do you get a Python
shell?

I appreciate that the ability to identify and report the errors encountered
here could be improved.

**Comment by petmakris** [comment] 2016-10-16 13:50
Yes I do: 

```
~ > ssh localhost python
print 'hello world'[Ctrl+D]
hello world
~ >
```

**Comment by petmakris** [comment] 2016-10-16 13:53
Closing this issue until ability to identify and report errors encountered is improved.

**Comment by lordmauve** [comment] 2016-10-16 19:24
This is a genuine issue; I'd rather keep it open.

**Comment by lordmauve** [comment] 2016-10-17 20:40
Did you get the error message line

    [localhost] bash: /usr/bin/python2: No such file or directory

? If this is the problem, it's relatively easy to fix; just add (before connection):

    Tunnel.python2 = 'python'

**Comment by lordmauve** [comment] 2017-06-01 21:55
This seems to be the situation on an out-of-the-box Mac OS X Sierra. I believe this is a duplicate of #14.

The solution is documented here: http://chopsticks.readthedocs.io/en/latest/howto.html#how-to-customise-interpreter-paths

**Closed by lordmauve** 2017-06-01 21:55 UTC
